version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: dotnet-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: react-frontend
    depends_on:
      - backend

  otel-collector:
  image: otel/opentelemetry-collector:latest
  volumes:
    - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
  command: ["--config=/etc/otelcol/config.yaml"]
  ports:
    - "4317:4317"    