version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: dotnet-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: react-frontend
    depends_on:
      - backend