version: "3.8"

services:

  backend:
    build:
      context: ./backend
    container_name: dotnet-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"